/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "var(--color-surface-container-lowest, #0d0e13)",
        "surface-container-low": "var(--color-surface-container-low, #1a1b21)",
        "surface-container": "var(--color-surface-container, #1e1f25)",
        "surface-container-high": "var(--color-surface-container-high, #292a2f)",
        "surface-container-highest": "var(--color-surface-container-highest, #34343a)",
        "surface-dim": "var(--color-surface-dim, #121318)",
        "surface-bright": "var(--color-surface-bright, #38393f)",
        "surface-variant": "var(--color-surface-variant, #34343a)",
        "surface": "var(--color-surface, #121318)",
        "background": "var(--color-background, #121318)",
        "on-background": "var(--color-on-background, #e3e1e9)",
        "on-surface": "var(--color-on-surface, #e3e1e9)",
        "on-surface-variant": "var(--color-on-surface-variant, #e5beb2)",
        "outline": "var(--color-outline, #ac897e)",
        "outline-variant": "var(--color-outline-variant, #5c4037)",
        "secondary-fixed-dim": "#ffb95f",
        "on-primary-fixed-variant": "#822700",
        "primary-fixed-dim": "#ffb59c",
        "on-tertiary": "#3c0091",
        "secondary": "var(--color-secondary, #ffb95f)",
        "primary-container": "var(--color-primary-container, #ff5708)",
        "on-tertiary-fixed-variant": "#5516be",
        "inverse-on-surface": "var(--color-inverse-on-surface, #2f3036)",
        "inverse-primary": "#aa3600",
        "primary-fixed": "#ffdbcf",
        "primary": "var(--color-primary, #ffb59c)",
        "on-secondary-container": "#5b3800",
        "tertiary-fixed": "#e9ddff",
        "on-primary-container": "#511500",
        "on-secondary": "#472a00",
        "on-primary-fixed": "#390c00",
        "secondary-container": "var(--color-secondary-container, #ee9800)",
        "on-tertiary-fixed": "#23005c",
        "surface-tint": "var(--color-primary-container, #ff5708)",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#653e00",
        "on-secondary-fixed": "#2a1700",
        "secondary-fixed": "#ffddb8",
        "inverse-surface": "var(--color-inverse-surface, #e3e1e9)",
        "on-tertiary-container": "#340080",
        "on-error": "#ffffff",
        "tertiary": "#d0bcff",
        "tertiary-fixed-dim": "#d0bcff",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#a078ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "margin": "3rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "gutter-mobile": "0.75rem"
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-hero": ["Geist", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "display-hero-mobile": ["Geist", "sans-serif"]
      },
      fontSize: {
        "code-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.04em", fontWeight: "600" }],
        "code-md": ["13px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.011em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "-0.006em", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.03em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
