/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Figma Exact Color System
        figma: {
          canvas: "#F7F5F0",
          card: "#FFFFFF",
          border: "#E8E4DC",
          "border-subtle": "#EFECE6",
          sidebar: "#181311",
          "sidebar-hover": "#241E1C",
          "sidebar-active": "#26201D",
          "sidebar-cta": "#F3E8DC",
          primary: "#181311",
          "primary-hover": "#2A2422",
          accent: "#D97736",
          "accent-hover": "#E28543",
          "accent-light": "#FCEFDF",
          "text-dark": "#191513",
          "text-muted": "#706864",
          "status-green": "#1D7A46",
          "status-green-bg": "#EAF5EE",
          "status-green-border": "#D1EBD9",
          "status-amber": "#B8621B",
          "status-amber-bg": "#FEF5EB",
          "status-amber-border": "#FCE2C4",
        },

        // VeraOS Official Color System
        vera: {
          bg: "#F7F5F0",
          deep: "#181311",
          cocoa: "#26201D",
          surface: "#FFFFFF",
          elevated: "#FFFFFF",
          warm: "#706864",
          primary: "#181311",
          bright: "#D97736",
          amber: "#B8621B",
          cream: "#F3E8DC",
          white: "#FFFFFF",
          muted: "#706864",
          border: "#E8E4DC",
        },

        // Theme semantic mappings
        background: "#F7F5F0",
        surface: "#FFFFFF",
        "surface-container-lowest": "#F7F5F0",
        "surface-container-low": "#FAF8F5",
        "surface-container": "#FFFFFF",
        "surface-container-high": "#F5F2EB",
        "surface-container-highest": "#E8E4DC",
        "on-background": "#191513",
        "on-surface": "#191513",
        "on-surface-variant": "#706864",
        outline: "#706864",
        "outline-variant": "#E8E4DC",

        // Verification Accents
        primary: {
          DEFAULT: "#181311",
          hover: "#2A2422",
          active: "#0D0A09",
          container: "#181311",
        },
        secondary: {
          DEFAULT: "#D97736",
          hover: "#E28543",
          container: "#FCEFDF",
        },
        status: {
          verified: "#1D7A46",
          "verified-bg": "#EAF5EE",
          "verified-border": "#D1EBD9",
          failed: "#DC2626",
          "failed-bg": "#FEF2F2",
          "failed-border": "#FECACA",
          unverifiable: "#B8621B",
          "unverifiable-bg": "#FEF5EB",
          "unverifiable-border": "#FCE2C4",
        },
        error: {
          DEFAULT: "#DC2626",
          container: "#FEF2F2",
          "on-error-container": "#991B1B",
        },
      },
      fontFamily: {
        heading: ["Poppins", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "code-md": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Poppins", "sans-serif"],
        "headline-sm": ["Poppins", "sans-serif"],
        "headline-md": ["Poppins", "sans-serif"],
        "headline-lg": ["Poppins", "sans-serif"],
        "display-hero": ["Poppins", "sans-serif"],
      },
    },
  },
  plugins: [],
}
