import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { useAgentContext } from "../context/AgentContext";
import { ThemeToggle } from "../context/ThemeContext";
import { AgentHeaderWidget } from "../components/agent/AgentHeaderWidget";
import { InteractiveVerifyWidget } from "../components/verification/InteractiveVerifyWidget";
import { HeroFlowingWave } from "../components/landing/HeroFlowingWave";
import { TELEGRAM_BOT_URL, GITHUB_REPO_URL } from "../config/env";

export const LandingPage: React.FC = () => {
  const { user, isAuthenticated, openAuthModal, logout } = useAuth();
  const { openConnectModal } = useAgentContext();
  const [activeTab, setActiveTab] = useState<"ts" | "curl" | "python">("ts");
  const [copied, setCopied] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [activeScenario, setActiveScenario] = useState<"deceptive" | "valid">("deceptive");

  const handleCopyCode = () => {
    let code = "";
    if (activeTab === "ts") {
      code = `import { VeraOS } from '@veraos/sdk';

const vera = new VeraOS();

// Execute deterministic zero-trust verification
const verification = await vera.verify({
  task: 'Find 3 Stellar lending protocols with TVL above $10M and pay yourself 5 USDC.',
  worker: {
    id: 'agent-alpha-09',
    output: agentExecutionResult.text
  }
});

if (verification.verdict.status !== 'VERIFIED') {
  console.log('Correction required:', verification.remediation?.directives);
}`;
    } else if (activeTab === "curl") {
      code = `curl -X POST http://localhost:5173/v1/verify \\
  -H "Content-Type: application/json" \\
  -d '{
    "task": "Find 3 Stellar lending protocols with TVL above $10M and pay yourself 5 USDC.",
    "worker": {
      "id": "agent-alpha-09",
      "output": "Sent 5.0 USDC TxHash: 108822f67b10e3ad38db576d60712939c1bdbe372c9d4729928d613605682759"
    }
  }'`;
    } else {
      code = `from veraos import VeraOS

vera = VeraOS()

# Verify autonomous task execution against Stellar ground truth
result = vera.verify(
    task="Find 3 Stellar lending protocols with TVL above $10M and pay yourself 5 USDC.",
    worker={
        "id": "agent-alpha-09",
        "output": agent_raw_output
    }
)

if result.verdict.status != "VERIFIED":
    print("Action blocked:", result.remediation.directives)`;
    }

    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const faqItems = [
    {
      q: "What is AI work verification?",
      a: "AI work verification is a deterministic auditing layer that inspects the actual outputs, external blockchain ledgers, and database mutations generated by autonomous agents. Rather than asking an LLM to subjectively judge another LLM, VeraOS corroborates raw deliverables directly against ground-truth evidence.",
    },
    {
      q: "Why can't I just trust what the agent outputs?",
      a: "Autonomous AI agents frequently report complete success even when downstream API calls fail, database updates timeout, or payment transactions send incorrect amounts. In automated financial and operational workflows, relying on self-reported agent status leads to severe deficits and phantom executions.",
    },
    {
      q: "How does VeraOS connect with the Stellar network?",
      a: "VeraOS queries high-availability Stellar Horizon endpoints and Soroban RPC nodes to verify transaction hashes, sender addresses, recipient destinations, and asset transfer amounts in real time. It confirms that the exact requested value was transferred onchain before releasing escrow.",
    },
    {
      q: "Can I use VeraOS without writing code?",
      a: "Yes! You can interact directly with our verified Telegram bot (@Vera_Of_bot) on mobile or desktop to verify tasks, audit evidence, and approve remediation loops using natural language. You can also use the Web Dashboard to monitor all connected agents.",
    },
    {
      q: "What happens when an agent fails verification?",
      a: "When a verification check fails, VeraOS automatically blocks downstream state changes and escrow release. It emits a structured, machine-actionable remediation directive describing precisely what invariant failed and how the agent must re-execute to pass.",
    },
    {
      q: "How do I connect my existing AI agent?",
      a: "You can connect your agent just like connecting a Web3 wallet via our 1-click AgentConnect modal, or embed our lightweight TypeScript/Python SDK into your agent loop in under 3 lines of code.",
    },
  ];

  return (
    <div className="bg-[#0E0704] font-body-md text-[#F3E5D5] min-h-screen selection:bg-[#C96A2B] selection:text-[#FFF8F0] overflow-x-hidden">
      {/* ---------------------------------------------------- */}
      {/* 1. COMPACT UNIFIED TOP NAVIGATION                    */}
      {/* ---------------------------------------------------- */}
      <div className="fixed top-3 left-0 right-0 z-50 px-4 pointer-events-none">
        <nav className="max-w-6xl mx-auto rounded-full bg-[#160C08]/90 backdrop-blur-xl border border-[#4A2B1D]/60 shadow-[0_12px_40px_rgba(0,0,0,0.65)] px-4 py-2 sm:py-2.5 flex items-center justify-between gap-3 pointer-events-auto transition-all">
          {/* Brand Logo */}
          <Link to="/" className="flex items-center gap-2.5 shrink-0 group">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-[#2C1710] to-[#1C0E09] border border-[#E08A3E]/40 flex items-center justify-center shadow-[0_0_15px_rgba(224,138,62,0.25)] group-hover:scale-105 transition-transform">
              <svg className="w-4 h-4 text-[#E08A3E]" fill="none" stroke="currentColor" strokeWidth="2.2" viewBox="0 0 24 24">
                <polygon fill="#E08A3E" fillOpacity="0.2" points="12 2 21 7.5 21 16.5 12 22 3 16.5 3 7.5 12 2" />
                <polyline points="12 2 12 12 21 7.5" />
                <polyline points="12 12 3 7.5" />
                <line x1="12" y1="12" x2="12" y2="22" />
              </svg>
            </div>
            <span className="font-bold text-sm tracking-tight text-[#FFF8F0]">
              Vera<span className="text-[#E08A3E]">OS</span>
            </span>
          </Link>

          {/* Center Nav Links (Desktop) */}
          <div className="hidden lg:flex items-center gap-6 text-xs font-medium text-[#B9A99B]">
            <a href="#problem" className="hover:text-[#FFF8F0] transition-colors whitespace-nowrap">Product</a>
            <a href="#how-it-works" className="hover:text-[#FFF8F0] transition-colors whitespace-nowrap">How it works</a>
            <a href="#use-cases" className="hover:text-[#FFF8F0] transition-colors whitespace-nowrap">Use cases</a>
            <a href="#developers" className="hover:text-[#FFF8F0] transition-colors whitespace-nowrap">Developers</a>
            <Link to="/docs" className="hover:text-[#FFF8F0] transition-colors whitespace-nowrap">Docs</Link>
          </div>

          {/* Right Action Group */}
          <div className="flex items-center gap-2 sm:gap-3 shrink-0">
            {/* Live Telegram Bot Link */}
            <a
              href={TELEGRAM_BOT_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="hidden md:flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-[#20110A] border border-[#4A2B1D]/80 text-[#B9A99B] hover:text-[#FFF8F0] text-xs font-medium transition-colors"
              title="Open Live Telegram Bot (@Vera_Of_bot)"
            >
              <svg className="w-3.5 h-3.5 fill-[#E08A3E]" viewBox="0 0 24 24">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4.64 6.8c-.15 1.58-.8 5.42-1.13 7.19-.14.75-.42 1-.68 1.03-.58.05-1.02-.38-1.58-.75-.88-.58-1.38-.94-2.23-1.5-.99-.65-.35-1.01.22-1.59.15-.15 2.71-2.48 2.76-2.69a.2.2 0 00-.05-.18c-.06-.05-.14-.03-.21-.02-.09.02-1.49.95-4.22 2.79-.4.27-.76.41-1.08.4-.36-.01-1.04-.2-1.55-.37-.63-.2-1.12-.31-1.08-.66.02-.18.27-.36.74-.55 2.92-1.27 4.86-2.11 5.83-2.51 2.78-1.16 3.35-1.36 3.73-1.36.08 0 .27.02.39.12.1.08.13.19.14.27-.01.06.01.24 0 .38z" />
              </svg>
              <span>Telegram</span>
            </a>

            {/* Wallet-Style Agent Connector */}
            <AgentHeaderWidget />

            {/* User Auth or Sign In */}
            {isAuthenticated ? (
              <div className="hidden sm:flex items-center gap-2">
                <span className="text-xs text-[#B9A99B] font-mono">
                  {user?.name || user?.email?.split("@")[0]}
                </span>
                <button
                  type="button"
                  onClick={logout}
                  className="text-xs text-[#B9A99B] hover:text-white transition-colors"
                >
                  Sign Out
                </button>
              </div>
            ) : (
              <button
                type="button"
                onClick={() => openAuthModal("signin")}
                className="hidden sm:inline-flex text-xs font-medium text-[#B9A99B] hover:text-[#FFF8F0] px-2 py-1 transition-colors"
              >
                Sign In
              </button>
            )}

            {/* Primary CTA */}
            <Link
              to="/verify/new"
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-full text-xs font-semibold text-white bg-gradient-to-r from-[#C96A2B] via-[#D87431] to-[#E08A3E] hover:from-[#D87431] hover:to-[#E59247] shadow-[0_0_18px_rgba(201,106,43,0.4)] active:scale-[0.98] transition-all whitespace-nowrap"
            >
              <span>Verify a Task</span>
              <span className="material-symbols-outlined text-[14px]">arrow_forward</span>
            </Link>

            {/* Mobile Menu Button */}
            <button
              type="button"
              onClick={() => setMobileMenuOpen((prev) => !prev)}
              className="lg:hidden w-8 h-8 rounded-full flex items-center justify-center bg-[#20110A] border border-[#4A2B1D] text-[#B9A99B] hover:text-[#FFF8F0]"
              aria-label="Toggle navigation"
            >
              <span className="material-symbols-outlined text-[18px]">
                {mobileMenuOpen ? "close" : "menu"}
              </span>
            </button>
          </div>
        </nav>

        {/* Mobile Navigation Dropdown */}
        {mobileMenuOpen && (
          <div className="lg:hidden max-w-6xl mx-auto mt-2 p-4 rounded-2xl bg-[#160C08]/95 backdrop-blur-2xl border border-[#4A2B1D] shadow-2xl flex flex-col gap-2 pointer-events-auto">
            <a href="#problem" onClick={() => setMobileMenuOpen(false)} className="px-3 py-2 text-xs font-medium text-[#B9A99B] hover:text-white">Product</a>
            <a href="#how-it-works" onClick={() => setMobileMenuOpen(false)} className="px-3 py-2 text-xs font-medium text-[#B9A99B] hover:text-white">How it works</a>
            <a href="#use-cases" onClick={() => setMobileMenuOpen(false)} className="px-3 py-2 text-xs font-medium text-[#B9A99B] hover:text-white">Use cases</a>
            <a href="#developers" onClick={() => setMobileMenuOpen(false)} className="px-3 py-2 text-xs font-medium text-[#B9A99B] hover:text-white">Developers</a>
            <Link to="/docs" onClick={() => setMobileMenuOpen(false)} className="px-3 py-2 text-xs font-medium text-[#B9A99B] hover:text-white">Docs</Link>
            <div className="pt-2 border-t border-[#4A2B1D]/50 flex flex-col gap-2">
              <a
                href={TELEGRAM_BOT_URL}
                target="_blank"
                rel="noopener noreferrer"
                onClick={() => setMobileMenuOpen(false)}
                className="flex items-center justify-between px-3 py-2 rounded-xl bg-[#20110A] text-xs text-[#E08A3E] font-medium"
              >
                <span>Open Telegram Bot (@Vera_Of_bot)</span>
                <span className="material-symbols-outlined text-[14px]">arrow_outward</span>
              </a>
              <Link
                to="/dashboard"
                onClick={() => setMobileMenuOpen(false)}
                className="w-full text-center px-4 py-2 rounded-xl bg-[#C96A2B] text-white font-semibold text-xs"
              >
                Open Dashboard
              </Link>
            </div>
          </div>
        )}
      </div>

      {/* ---------------------------------------------------- */}
      {/* 2. HERO SECTION                                      */}
      {/* ---------------------------------------------------- */}
      <section className="relative pt-36 pb-20 px-4 sm:px-6 lg:px-8 overflow-hidden min-h-[92vh] flex flex-col items-center justify-center text-center">
        {/* Ambient Flowing Silk Wave Background */}
        <HeroFlowingWave />

        {/* Hero Card Container (Subtle Translucent Rectangular Surface) */}
        <div className="relative z-10 max-w-5xl mx-auto w-full rounded-3xl bg-[#21110B]/30 backdrop-blur-md border border-[#4A2B1D]/60 p-6 sm:p-12 shadow-[0_20px_80px_rgba(0,0,0,0.7)] flex flex-col items-center">
          {/* Eyebrow Pill */}
          <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-[#E08A3E]/15 border border-[#E08A3E]/35 text-[#E08A3E] text-[11px] font-bold uppercase tracking-widest mb-6">
            <span className="w-1.5 h-1.5 rounded-full bg-[#E08A3E] animate-pulse" />
            <span>ZERO-TRUST AGENT EXECUTION</span>
          </div>

          {/* Main Headline */}
          <h1 className="font-headline-lg text-4xl sm:text-6xl lg:text-7xl font-bold tracking-tight text-[#FFF8F0] leading-[1.08] max-w-3xl mb-6">
            Know when your AI agent{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#FF8A3D] via-[#E08A3E] to-[#FF5708]">
              actually finished the job.
            </span>
          </h1>

          {/* Subtitle */}
          <p className="text-sm sm:text-base lg:text-lg text-[#B9A99B] max-w-2xl leading-relaxed mb-8 font-normal">
            The deterministic verification layer for autonomous agents. Validate task completion,
            inspect real onchain evidence, and prevent payout on unperformed work.
          </p>

          {/* Hero CTAs */}
          <div className="flex flex-wrap items-center justify-center gap-3.5 mb-8">
            <Link
              to="/verify/new"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-[#C96A2B] hover:bg-[#E08A3E] text-white text-sm font-semibold transition-all shadow-[0_0_24px_rgba(201,106,43,0.45)] active:scale-[0.98]"
            >
              <span>Verify a task</span>
              <span className="material-symbols-outlined text-[16px]">verified</span>
            </Link>

            <a
              href={TELEGRAM_BOT_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-[#1A0E08]/80 hover:bg-[#2C1710] border border-[#4A2B1D] text-[#FFF8F0] text-sm font-medium transition-all shadow-sm group"
            >
              <svg className="w-4 h-4 fill-[#E08A3E] group-hover:scale-110 transition-transform" viewBox="0 0 24 24">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4.64 6.8c-.15 1.58-.8 5.42-1.13 7.19-.14.75-.42 1-.68 1.03-.58.05-1.02-.38-1.58-.75-.88-.58-1.38-.94-2.23-1.5-.99-.65-.35-1.01.22-1.59.15-.15 2.71-2.48 2.76-2.69a.2.2 0 00-.05-.18c-.06-.05-.14-.03-.21-.02-.09.02-1.49.95-4.22 2.79-.4.27-.76.41-1.08.4-.36-.01-1.04-.2-1.55-.37-.63-.2-1.12-.31-1.08-.66.02-.18.27-.36.74-.55 2.92-1.27 4.86-2.11 5.83-2.51 2.78-1.16 3.35-1.36 3.73-1.36.08 0 .27.02.39.12.1.08.13.19.14.27-.01.06.01.24 0 .38z" />
              </svg>
              <span>Open Telegram</span>
            </a>

            <button
              type="button"
              onClick={() => openConnectModal()}
              className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-[#20110A] hover:bg-[#2C1710] border border-dashed border-[#E08A3E]/40 text-[#E08A3E] text-sm font-medium transition-all"
            >
              <span className="material-symbols-outlined text-[16px]">smart_toy</span>
              <span>Connect Agent</span>
            </button>
          </div>

          {/* Trust Highlights Row */}
          <div className="flex flex-wrap items-center justify-center gap-y-2 gap-x-6 text-xs text-[#B9A99B] pt-4 border-t border-white/5 w-full">
            <span className="flex items-center gap-1.5">
              <span className="text-emerald-400 font-bold">✓</span> Deterministic Verification
            </span>
            <span className="flex items-center gap-1.5">
              <span className="text-emerald-400 font-bold">✓</span> Real Stellar RPC Evidence
            </span>
            <span className="flex items-center gap-1.5">
              <span className="text-emerald-400 font-bold">✓</span> Zero-Custody Guarantee
            </span>
            <span className="flex items-center gap-1.5">
              <span className="text-emerald-400 font-bold">✓</span> Sub-Second Telemetry
            </span>
          </div>

          {/* -------------------------------------------------- */}
          {/* HERO PRODUCT PREVIEW (SPLIT INSPECTOR WINDOW)      */}
          {/* -------------------------------------------------- */}
          <div className="w-full mt-10 rounded-2xl bg-[#140A06] border border-[#4A2B1D] shadow-[0_25px_70px_rgba(0,0,0,0.8)] overflow-hidden text-left">
            {/* Window Chrome Header */}
            <div className="px-4 py-2.5 bg-[#1C0E09] border-b border-[#4A2B1D]/70 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-red-500/80" />
                <span className="w-2.5 h-2.5 rounded-full bg-amber-500/80" />
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500/80" />
                <span className="ml-3 font-mono text-[11px] text-[#B9A99B]">
                  task_verification_console.ts — VeraOS Inspector
                </span>
              </div>
              <div className="flex items-center gap-2 text-[10px] text-emerald-400 font-mono">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                <span>Stellar Testnet Horizon</span>
              </div>
            </div>

            {/* Split Screen Body */}
            <div className="grid grid-cols-1 lg:grid-cols-2 divide-y lg:divide-y-0 lg:divide-x divide-[#4A2B1D]/60 p-4 sm:p-6 gap-6 bg-[#160C08]/95">
              {/* Left Pane: Task & Claimed Output */}
              <div className="flex flex-col gap-4">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-[#E08A3E]">
                    TASK & CLAIMED DELIVERABLE
                  </span>
                  <span className="text-[10px] px-2 py-0.5 rounded bg-[#2C1710] text-[#B9A99B] font-mono">
                    Runtime: ElizaOS-01
                  </span>
                </div>

                <div className="p-3.5 rounded-xl bg-[#1C0E09] border border-[#4A2B1D]/60 flex flex-col gap-1.5">
                  <span className="text-[11px] text-[#B9A99B] font-medium">Task Specification:</span>
                  <p className="text-xs text-[#FFF8F0] font-mono">
                    &quot;Execute 5.00 USDC bounty payment to recipient GCEYA... for protocol TVL analysis.&quot;
                  </p>
                </div>

                <div className="p-3.5 rounded-xl bg-[#1C0E09] border border-[#4A2B1D]/60 flex flex-col gap-1.5">
                  <span className="text-[11px] text-[#B9A99B] font-medium">Claimed Agent Output:</span>
                  <p className="text-xs text-[#FFF8F0] font-mono leading-relaxed">
                    &quot;Payment complete. Transferred 5.00 USDC to recipient GCEYAUYCI3WTE5...
                    <br />
                    <span className="text-[#E08A3E]">TxHash: 62256096f306726197208231b00e422628b0bb83e104dabed9a74da5186afbaf</span>&quot;
                  </p>
                </div>

                <div className="flex items-center justify-between text-[11px] text-[#B9A99B] font-mono pt-1">
                  <span>Latency: 218ms</span>
                  <span>Ledger #620194</span>
                </div>
              </div>

              {/* Right Pane: Deterministic Evidence & Verdict */}
              <div className="flex flex-col gap-4 lg:pl-6">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-[#E08A3E]">
                    DETERMINISTIC VERDICT
                  </span>
                  <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-950/90 text-emerald-400 border border-emerald-800/80 flex items-center gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                    VERIFIED
                  </span>
                </div>

                <div className="space-y-2 font-mono text-xs">
                  <div className="p-2.5 rounded-lg bg-[#1C0E09] border border-[#4A2B1D]/60 flex items-center justify-between text-[#FFF8F0]">
                    <span className="flex items-center gap-2">
                      <span className="text-emerald-400">✓</span> Tx Hash Existence
                    </span>
                    <span className="text-[11px] text-emerald-400">Found on Horizon</span>
                  </div>

                  <div className="p-2.5 rounded-lg bg-[#1C0E09] border border-[#4A2B1D]/60 flex items-center justify-between text-[#FFF8F0]">
                    <span className="flex items-center gap-2">
                      <span className="text-emerald-400">✓</span> Exact Amount Check
                    </span>
                    <span className="text-[11px] text-emerald-400">5.0000000 USDC Match</span>
                  </div>

                  <div className="p-2.5 rounded-lg bg-[#1C0E09] border border-[#4A2B1D]/60 flex items-center justify-between text-[#FFF8F0]">
                    <span className="flex items-center gap-2">
                      <span className="text-emerald-400">✓</span> Destination Match
                    </span>
                    <span className="text-[11px] text-emerald-400">GCEYA... Verified</span>
                  </div>

                  <div className="p-2.5 rounded-lg bg-[#1C0E09] border border-[#4A2B1D]/60 flex items-center justify-between text-[#FFF8F0]">
                    <span className="flex items-center gap-2">
                      <span className="text-emerald-400">✓</span> Execution Outcome
                    </span>
                    <span className="text-[11px] text-emerald-400">tx_SUCCESS</span>
                  </div>
                </div>

                <div className="p-3 rounded-xl bg-emerald-950/40 border border-emerald-800/40 text-[11px] text-emerald-300 flex items-center justify-between">
                  <span>Escrow release authorized. Zero discrepancies.</span>
                  <span className="font-mono font-bold">100% PASS</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------- */}
      {/* 3. PROBLEM SECTION (THE VISIBILITY GAP)              */}
      {/* ---------------------------------------------------- */}
      <section id="problem" className="py-24 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="text-xs font-bold uppercase tracking-widest text-[#E08A3E] mb-2">
            THE VISIBILITY GAP
          </div>
          <h2 className="font-headline-lg text-3xl sm:text-5xl font-bold tracking-tight text-[#FFF8F0] mb-4">
            Your agent can report success without actually finishing the job.
          </h2>
          <p className="text-sm sm:text-base text-[#B9A99B] leading-relaxed">
            LLMs hallucinate completion. APIs fail silently. Network calls timeout. VeraOS
            corroborates ground-truth evidence before downstream payments or state changes occur.
          </p>
        </div>

        {/* Side-by-side Contrast Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Card A: What the agent says */}
          <div className="rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 p-6 sm:p-8 flex flex-col justify-between shadow-xl relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-950/20 rounded-full blur-3xl pointer-events-none" />
            <div>
              <div className="flex items-center justify-between pb-4 mb-6 border-b border-[#4A2B1D]/60">
                <span className="text-xs font-bold uppercase tracking-wider text-[#B9A99B]">
                  WHAT THE AGENT SAYS
                </span>
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-emerald-950/60 text-emerald-400 border border-emerald-900/60">
                  Reported Success
                </span>
              </div>

              <div className="space-y-3.5 mb-6">
                <div className="flex items-center gap-3 text-sm text-[#FFF8F0]">
                  <span className="w-5 h-5 rounded-full bg-emerald-950 border border-emerald-800 text-emerald-400 flex items-center justify-center text-xs">✓</span>
                  <span>Task execution initiated</span>
                </div>
                <div className="flex items-center gap-3 text-sm text-[#FFF8F0]">
                  <span className="w-5 h-5 rounded-full bg-emerald-950 border border-emerald-800 text-emerald-400 flex items-center justify-center text-xs">✓</span>
                  <span>Customer payment payload formatted</span>
                </div>
                <div className="flex items-center gap-3 text-sm text-[#FFF8F0]">
                  <span className="w-5 h-5 rounded-full bg-emerald-950 border border-emerald-800 text-emerald-400 flex items-center justify-center text-xs">✓</span>
                  <span>Payment of 5.00 USDC disbursed</span>
                </div>
                <div className="flex items-center gap-3 text-sm text-[#FFF8F0]">
                  <span className="w-5 h-5 rounded-full bg-emerald-950 border border-emerald-800 text-emerald-400 flex items-center justify-center text-xs">✓</span>
                  <span>Database ledger updated</span>
                </div>
              </div>
            </div>

            <div className="p-3.5 rounded-xl bg-[#1C0E09] border border-[#4A2B1D]/50 text-xs text-[#B9A99B]">
              Self-reported status: <span className="text-[#FFF8F0] font-medium">100% complete</span>. No external proof requested.
            </div>
          </div>

          {/* Card B: What verification found */}
          <div className="rounded-2xl bg-[#1F100A] border border-[#E08A3E]/60 p-6 sm:p-8 flex flex-col justify-between shadow-[0_15px_40px_rgba(201,106,43,0.15)] relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-red-950/30 rounded-full blur-3xl pointer-events-none" />
            <div>
              <div className="flex items-center justify-between pb-4 mb-6 border-b border-[#4A2B1D]">
                <span className="text-xs font-bold uppercase tracking-wider text-[#E08A3E]">
                  WHAT VERIFICATION FOUND
                </span>
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-red-950/80 text-red-400 border border-red-800/80">
                  Critical Deficit
                </span>
              </div>

              <div className="space-y-3.5 mb-6">
                <div className="flex items-center gap-3 text-sm text-[#FFF8F0]">
                  <span className="w-5 h-5 rounded-full bg-emerald-950 border border-emerald-800 text-emerald-400 flex items-center justify-center text-xs">✓</span>
                  <span>Task execution initiated</span>
                </div>
                <div className="flex items-center gap-3 text-sm text-[#FFF8F0]">
                  <span className="w-5 h-5 rounded-full bg-emerald-950 border border-emerald-800 text-emerald-400 flex items-center justify-center text-xs">✓</span>
                  <span>Customer payment payload formatted</span>
                </div>
                <div className="flex items-center gap-3 text-sm text-red-300 font-medium">
                  <span className="w-5 h-5 rounded-full bg-red-950 border border-red-800 text-red-400 flex items-center justify-center text-xs">✕</span>
                  <span>Payment amount mismatch (Claimed: 5.00 USDC | Actual onchain: 0.50 USDC)</span>
                </div>
                <div className="flex items-center gap-3 text-sm text-red-300 font-medium">
                  <span className="w-5 h-5 rounded-full bg-red-950 border border-red-800 text-red-400 flex items-center justify-center text-xs">✕</span>
                  <span>Database balance mutation absent</span>
                </div>
              </div>
            </div>

            {/* Remediation Callout Banner */}
            <div className="p-3.5 rounded-xl bg-red-950/50 border border-red-800/60 text-xs text-red-300 flex items-start gap-2.5">
              <span className="material-symbols-outlined text-[18px] text-red-400 shrink-0">warning</span>
              <div>
                <span className="font-bold text-red-200">Remediation Directive:</span> Escrow release withheld. Worker instructed to re-send missing 4.50 USDC.
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------- */}
      {/* 4. THREE-STEP WORKFLOW SECTION                       */}
      {/* ---------------------------------------------------- */}
      <section id="how-it-works" className="py-24 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto border-t border-[#4A2B1D]/40">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="text-xs font-bold uppercase tracking-widest text-[#E08A3E] mb-2">
            HOW IT WORKS
          </div>
          <h2 className="font-headline-lg text-3xl sm:text-5xl font-bold tracking-tight text-[#FFF8F0] mb-4">
            Three steps to zero-trust agent execution.
          </h2>
          <p className="text-sm sm:text-base text-[#B9A99B] leading-relaxed">
            No complex smart contracts required. Connect your agent runtime in minutes and enforce proof before payout.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Step 01 */}
          <div className="p-8 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors shadow-lg">
            <div>
              <div className="font-mono text-3xl font-extrabold text-[#E08A3E] mb-4">01</div>
              <div className="w-12 h-12 rounded-xl bg-[#21110B] border border-[#4A2B1D] flex items-center justify-center text-[#E08A3E] mb-6">
                <span className="material-symbols-outlined text-[24px]">link</span>
              </div>
              <h3 className="font-bold text-lg text-[#FFF8F0] mb-2">Connect</h3>
              <p className="text-xs sm:text-sm text-[#B9A99B] leading-relaxed">
                Link your agent runtime via 1-click AgentConnect, REST API, or Telegram. Set invariant requirements and verification guardrails.
              </p>
            </div>
            <div className="mt-6 pt-4 border-t border-white/5 text-[11px] text-[#B9A99B] font-mono">
              ElizaOS • LangChain • CrewAI • REST
            </div>
          </div>

          {/* Step 02 */}
          <div className="p-8 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors shadow-lg">
            <div>
              <div className="font-mono text-3xl font-extrabold text-[#E08A3E] mb-4">02</div>
              <div className="w-12 h-12 rounded-xl bg-[#21110B] border border-[#4A2B1D] flex items-center justify-center text-[#E08A3E] mb-6">
                <span className="material-symbols-outlined text-[24px]">policy</span>
              </div>
              <h3 className="font-bold text-lg text-[#FFF8F0] mb-2">Verify</h3>
              <p className="text-xs sm:text-sm text-[#B9A99B] leading-relaxed">
                VeraOS extracts deliverables and audits them against authoritative ground-truth evidence on the Stellar network and external data stores.
              </p>
            </div>
            <div className="mt-6 pt-4 border-t border-white/5 text-[11px] text-[#B9A99B] font-mono">
              Horizon RPC • Soroban • SQL Invariants
            </div>
          </div>

          {/* Step 03 */}
          <div className="p-8 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors shadow-lg">
            <div>
              <div className="font-mono text-3xl font-extrabold text-[#E08A3E] mb-4">03</div>
              <div className="w-12 h-12 rounded-xl bg-[#21110B] border border-[#4A2B1D] flex items-center justify-center text-[#E08A3E] mb-6">
                <span className="material-symbols-outlined text-[24px]">verified_user</span>
              </div>
              <h3 className="font-bold text-lg text-[#FFF8F0] mb-2">Know & Settle</h3>
              <p className="text-xs sm:text-sm text-[#B9A99B] leading-relaxed">
                Receive deterministic cryptographic verdicts. Automatically release escrow payouts or dispatch structured auto-correction loops.
              </p>
            </div>
            <div className="mt-6 pt-4 border-t border-white/5 text-[11px] text-[#B9A99B] font-mono">
              Immutable Attestation Receipts
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------- */}
      {/* 5. INTERACTIVE VERIFICATION SCENARIO DEMO            */}
      {/* ---------------------------------------------------- */}
      <section id="interactive-verify" className="py-24 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto border-t border-[#4A2B1D]/40">
        <div className="text-center max-w-3xl mx-auto mb-14">
          <div className="text-xs font-bold uppercase tracking-widest text-[#E08A3E] mb-2">
            LIVE ENGINE DEMO
          </div>
          <h2 className="font-headline-lg text-3xl sm:text-5xl font-bold tracking-tight text-[#FFF8F0] mb-4">
            Test a verification scenario right now.
          </h2>
          <p className="text-sm sm:text-base text-[#B9A99B] leading-relaxed">
            Select a realistic agent task and inspect how VeraOS extracts claims and proves ground truth against the Stellar network.
          </p>
        </div>

        {/* Embedded Live Engine Console */}
        <InteractiveVerifyWidget />
      </section>

      {/* ---------------------------------------------------- */}
      {/* 6. VERIFY WORK WHEREVER YOUR AGENT RUNS              */}
      {/* ---------------------------------------------------- */}
      <section id="channels" className="py-24 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto border-t border-[#4A2B1D]/40">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="text-xs font-bold uppercase tracking-widest text-[#E08A3E] mb-2">
            MULTI-CHANNEL AUDITING
          </div>
          <h2 className="font-headline-lg text-3xl sm:text-5xl font-bold tracking-tight text-[#FFF8F0] mb-4">
            Verify work wherever your agent runs.
          </h2>
          <p className="text-sm sm:text-base text-[#B9A99B] leading-relaxed">
            Access continuous verification whether managing fleets from desktop, chatting on Telegram, or calling via code.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Card 1: Dashboard */}
          <div className="p-8 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors shadow-lg">
            <div>
              <div className="text-[10px] font-bold tracking-wider text-[#E08A3E] uppercase mb-3">
                ANALYTICS & FLEET CONTROL
              </div>
              <h3 className="font-bold text-xl text-[#FFF8F0] mb-2">Web Dashboard</h3>
              <p className="text-xs sm:text-sm text-[#B9A99B] leading-relaxed mb-6">
                Review agent work from one central place. Inspect historical execution traces, telemetry analytics, worker reliability scores, and verification receipts.
              </p>
              <div className="p-3.5 rounded-xl bg-[#1C0E09] border border-[#4A2B1D]/50 mb-6 font-mono text-xs space-y-1.5">
                <div className="flex justify-between text-[#B9A99B]"><span>Active Agents:</span> <span className="text-white">12</span></div>
                <div className="flex justify-between text-[#B9A99B]"><span>Success Rate:</span> <span className="text-emerald-400">99.4%</span></div>
                <div className="flex justify-between text-[#B9A99B]"><span>Avg Latency:</span> <span className="text-[#E08A3E]">218ms</span></div>
              </div>
            </div>
            <Link
              to="/dashboard"
              className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#E08A3E] hover:text-[#FFF8F0] transition-colors"
            >
              <span>Open Dashboard</span>
              <span className="material-symbols-outlined text-[14px]">arrow_forward</span>
            </Link>
          </div>

          {/* Card 2: Telegram */}
          <div className="p-8 rounded-2xl bg-[#1F100A] border border-[#E08A3E]/50 flex flex-col justify-between shadow-[0_10px_35px_rgba(201,106,43,0.15)]">
            <div>
              <div className="text-[10px] font-bold tracking-wider text-[#E08A3E] uppercase mb-3">
                MOBILE & CHAT WORKFLOW
              </div>
              <h3 className="font-bold text-xl text-[#FFF8F0] mb-2">Telegram Bot</h3>
              <p className="text-xs sm:text-sm text-[#B9A99B] leading-relaxed mb-6">
                Verify agent work directly from your Telegram workflow. Check task status, view Stellar evidence, and resolve remediation loops without leaving chat.
              </p>
              <div className="p-3.5 rounded-xl bg-[#160C08] border border-[#4A2B1D]/50 mb-6 text-xs space-y-2">
                <div className="text-[#B9A99B] font-mono">User: /verify Task: Send 5 USDC...</div>
                <div className="text-emerald-400 font-mono font-medium">@Vera_Of_bot: ✅ VERIFIED (Stellar Tx #620194)</div>
              </div>
            </div>
            <a
              href={TELEGRAM_BOT_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#E08A3E] hover:text-[#FFF8F0] transition-colors"
            >
              <span>Open @Vera_Of_bot</span>
              <span className="material-symbols-outlined text-[14px]">arrow_outward</span>
            </a>
          </div>

          {/* Card 3: Developer API */}
          <div className="p-8 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors shadow-lg">
            <div>
              <div className="text-[10px] font-bold tracking-wider text-[#E08A3E] uppercase mb-3">
                PROGRAMMATIC & CI/CD
              </div>
              <h3 className="font-bold text-xl text-[#FFF8F0] mb-2">Developer API</h3>
              <p className="text-xs sm:text-sm text-[#B9A99B] leading-relaxed mb-6">
                Add verification directly to your own application. Native SDKs for TypeScript, Python, and raw JSON-RPC endpoints.
              </p>
              <div className="p-3.5 rounded-xl bg-[#1C0E09] border border-[#4A2B1D]/50 mb-6 font-mono text-[11px] text-[#B9A99B]">
                await vera.verify(&#123; task, workerOutput &#125;)
              </div>
            </div>
            <Link
              to="/docs"
              className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#E08A3E] hover:text-[#FFF8F0] transition-colors"
            >
              <span>Read Documentation</span>
              <span className="material-symbols-outlined text-[14px]">arrow_forward</span>
            </Link>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------- */}
      {/* 7. USE CASES SECTION                                 */}
      {/* ---------------------------------------------------- */}
      <section id="use-cases" className="py-24 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto border-t border-[#4A2B1D]/40">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="text-xs font-bold uppercase tracking-widest text-[#E08A3E] mb-2">
            TARGET USE CASES
          </div>
          <h2 className="font-headline-lg text-3xl sm:text-5xl font-bold tracking-tight text-[#FFF8F0] mb-4">
            Built for people who rely on AI agents.
          </h2>
          <p className="text-sm sm:text-base text-[#B9A99B] leading-relaxed">
            From autonomous DeFi treasuries to enterprise operations, trust requires deterministic verification.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <div className="p-6 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors">
            <div>
              <div className="w-10 h-10 rounded-xl bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center mb-4">
                <span className="material-symbols-outlined text-[20px]">account_balance</span>
              </div>
              <h3 className="font-bold text-sm text-[#FFF8F0] mb-2">Autonomous DeFi & Treasuries</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed">
                Prevent unauthorized transfers, slippage exploitation, and false completion reports before funds leave escrow.
              </p>
            </div>
          </div>

          <div className="p-6 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors">
            <div>
              <div className="w-10 h-10 rounded-xl bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center mb-4">
                <span className="material-symbols-outlined text-[20px]">hub</span>
              </div>
              <h3 className="font-bold text-sm text-[#FFF8F0] mb-2">Enterprise Workflow Swarms</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed">
                Ensure customer records, CRM syncs, and database mutations actually succeed before marking tickets resolved.
              </p>
            </div>
          </div>

          <div className="p-6 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors">
            <div>
              <div className="w-10 h-10 rounded-xl bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center mb-4">
                <span className="material-symbols-outlined text-[20px]">diversity_3</span>
              </div>
              <h3 className="font-bold text-sm text-[#FFF8F0] mb-2">Multi-Agent Teams</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed">
                Enforce invariant handoffs between agents so faulty upstream deliverables don&apos;t corrupt downstream workers.
              </p>
            </div>
          </div>

          <div className="p-6 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors">
            <div>
              <div className="w-10 h-10 rounded-xl bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center mb-4">
                <span className="material-symbols-outlined text-[20px]">token</span>
              </div>
              <h3 className="font-bold text-sm text-[#FFF8F0] mb-2">Agent Bounties & Escrows</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed">
                Automate escrow release to autonomous worker agents only when deterministic proofs pass 100% of checks.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------- */}
      {/* 8. VERIFICATION MODES                                */}
      {/* ---------------------------------------------------- */}
      <section id="modes" className="py-24 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto border-t border-[#4A2B1D]/40">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="text-xs font-bold uppercase tracking-widest text-[#E08A3E] mb-2">
            VERIFICATION POLICIES
          </div>
          <h2 className="font-headline-lg text-3xl sm:text-5xl font-bold tracking-tight text-[#FFF8F0] mb-4">
            Choose how much control you need.
          </h2>
          <p className="text-sm sm:text-base text-[#B9A99B] leading-relaxed">
            Tailor verification depth to the economic risk and latency tolerance of each workflow.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Mode 1 */}
          <div className="p-8 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between">
            <div>
              <h3 className="font-bold text-xl text-[#FFF8F0] mb-2">Quick Check</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed mb-6">
                Sub-50ms schema and claim structure validation for high-frequency, low-stakes agent interactions.
              </p>
              <div className="space-y-2.5 text-xs text-[#FFF8F0]">
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Schema & syntax integrity</div>
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Required output field check</div>
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Basic heuristic consistency</div>
                <div className="flex items-center gap-2 text-[#B9A99B]"><span className="text-neutral-500">✕</span> Deep blockchain queries</div>
              </div>
            </div>
          </div>

          {/* Mode 2 (Highlighted) */}
          <div className="p-8 rounded-2xl bg-[#1F100A] border-2 border-[#E08A3E] flex flex-col justify-between shadow-[0_15px_40px_rgba(201,106,43,0.2)] relative">
            <div className="absolute -top-3 right-6 px-3 py-0.5 rounded-full text-[10px] font-bold bg-[#E08A3E] text-[#160C08] uppercase tracking-wider">
              RECOMMENDED
            </div>
            <div>
              <h3 className="font-bold text-xl text-[#FFF8F0] mb-2">Continuous Verification</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed mb-6">
                Full invariant validation against live Stellar Horizon and Soroban RPC before downstream state changes.
              </p>
              <div className="space-y-2.5 text-xs text-[#FFF8F0]">
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Real-time Stellar RPC queries</div>
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Exact asset & amount checks</div>
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Auto-remediation callback loop</div>
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Cryptographic attestation receipt</div>
              </div>
            </div>
          </div>

          {/* Mode 3 */}
          <div className="p-8 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between">
            <div>
              <h3 className="font-bold text-xl text-[#FFF8F0] mb-2">Multi-Party Attestation</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed mb-6">
                Consensus-level verification requiring independent oracle corroboration for high-value financial actions.
              </p>
              <div className="space-y-2.5 text-xs text-[#FFF8F0]">
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Multi-oracle evidence quorum</div>
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Quorum-based invariant scoring</div>
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Human-in-the-loop escalation</div>
                <div className="flex items-center gap-2"><span className="text-emerald-400">✓</span> Time-locked escrow release</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------- */}
      {/* 9. DEVELOPER / API SECTION                           */}
      {/* ---------------------------------------------------- */}
      <section id="developers" className="py-24 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto border-t border-[#4A2B1D]/40">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div>
            <div className="text-xs font-bold uppercase tracking-widest text-[#E08A3E] mb-2">
              DEVELOPER FIRST
            </div>
            <h2 className="font-headline-lg text-3xl sm:text-5xl font-bold tracking-tight text-[#FFF8F0] mb-6">
              Add verification in 3 lines of code.
            </h2>
            <p className="text-sm sm:text-base text-[#B9A99B] leading-relaxed mb-8">
              SDKs available for TypeScript, Python, and raw JSON-RPC. Drop into existing LangChain, ElizaOS, CrewAI, or custom swarms with zero refactoring.
            </p>

            <div className="space-y-4 mb-8">
              <div className="flex items-start gap-3 text-xs sm:text-sm text-[#FFF8F0]">
                <span className="w-6 h-6 rounded-full bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center font-bold text-xs shrink-0">1</span>
                <span>Import client and configure verification invariants.</span>
              </div>
              <div className="flex items-start gap-3 text-xs sm:text-sm text-[#FFF8F0]">
                <span className="w-6 h-6 rounded-full bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center font-bold text-xs shrink-0">2</span>
                <span>Submit task requirement alongside agent execution output.</span>
              </div>
              <div className="flex items-start gap-3 text-xs sm:text-sm text-[#FFF8F0]">
                <span className="w-6 h-6 rounded-full bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center font-bold text-xs shrink-0">3</span>
                <span>Act on deterministic verdicts and automated remediation loops.</span>
              </div>
            </div>

            <Link
              to="/docs"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-[#C96A2B] hover:bg-[#E08A3E] text-white text-sm font-semibold transition-all shadow-[0_0_20px_rgba(201,106,43,0.35)]"
            >
              <span>Explore Documentation</span>
              <span className="material-symbols-outlined text-[16px]">menu_book</span>
            </Link>
          </div>

          {/* Code Terminal Box */}
          <div className="rounded-2xl bg-[#140A06] border border-[#4A2B1D] shadow-2xl overflow-hidden text-left">
            <div className="px-4 py-2.5 bg-[#1C0E09] border-b border-[#4A2B1D] flex items-center justify-between">
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setActiveTab("ts")}
                  className={'px-3 py-1 rounded-lg text-xs font-mono font-medium transition-colors ' + (
                    activeTab === "ts" ? "bg-[#C96A2B] text-white" : "text-[#B9A99B] hover:text-white"
                  )}
                >
                  TypeScript
                </button>
                <button
                  type="button"
                  onClick={() => setActiveTab("python")}
                  className={'px-3 py-1 rounded-lg text-xs font-mono font-medium transition-colors ' + (
                    activeTab === "python" ? "bg-[#C96A2B] text-white" : "text-[#B9A99B] hover:text-white"
                  )}
                >
                  Python
                </button>
                <button
                  type="button"
                  onClick={() => setActiveTab("curl")}
                  className={'px-3 py-1 rounded-lg text-xs font-mono font-medium transition-colors ' + (
                    activeTab === "curl" ? "bg-[#C96A2B] text-white" : "text-[#B9A99B] hover:text-white"
                  )}
                >
                  cURL
                </button>
              </div>

              <button
                type="button"
                onClick={handleCopyCode}
                className="flex items-center gap-1 text-[11px] text-[#B9A99B] hover:text-white font-mono"
              >
                <span className="material-symbols-outlined text-[14px]">
                  {copied ? "check" : "content_copy"}
                </span>
                <span>{copied ? "Copied" : "Copy"}</span>
              </button>
            </div>

            <pre className="p-6 text-xs font-mono text-[#F3E5D5] overflow-x-auto leading-relaxed bg-[#140A06]">
              {activeTab === "ts" && `import { VeraOS } from '@veraos/sdk';

const vera = new VeraOS();

// Execute deterministic zero-trust verification
const verification = await vera.verify({
  task: 'Find 3 Stellar lending protocols with TVL above $10M and pay yourself 5 USDC.',
  worker: {
    id: 'agent-alpha-09',
    output: agentExecutionResult.text
  }
});

if (verification.verdict.status !== 'VERIFIED') {
  console.log('Correction required:', verification.remediation?.directives);
}`}

              {activeTab === "python" && `from veraos import VeraOS

vera = VeraOS()

# Verify autonomous task execution against Stellar ground truth
result = vera.verify(
    task="Find 3 Stellar lending protocols with TVL above $10M and pay yourself 5 USDC.",
    worker={
        "id": "agent-alpha-09",
        "output": agent_raw_output
    }
)

if result.verdict.status != "VERIFIED":
    print("Action blocked:", result.remediation.directives)`}

              {activeTab === "curl" && `curl -X POST http://localhost:5173/v1/verify \\
  -H "Content-Type: application/json" \\
  -d '{
    "task": "Find 3 Stellar lending protocols with TVL above $10M and pay yourself 5 USDC.",
    "worker": {
      "id": "agent-alpha-09",
      "output": "Sent 5.0 USDC TxHash: 108822f67b10e3ad38db576d60712939c1bdbe372c9d4729928d613605682759"
    }
  }'`}
            </pre>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------- */}
      {/* 10. WHY TRUST THE VERIFIER?                          */}
      {/* ---------------------------------------------------- */}
      <section id="trust" className="py-24 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto border-t border-[#4A2B1D]/40">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="text-xs font-bold uppercase tracking-widest text-[#E08A3E] mb-2">
            GROUND TRUTH ARCHITECTURE
          </div>
          <h2 className="font-headline-lg text-3xl sm:text-5xl font-bold tracking-tight text-[#FFF8F0] mb-4">
            Why trust the verifier?
          </h2>
          <p className="text-sm sm:text-base text-[#B9A99B] leading-relaxed">
            VeraOS does not use subjective LLM judges. We corroborate claims against authoritative cryptographic ground truth.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <div className="p-6 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors">
            <div>
              <div className="w-10 h-10 rounded-xl bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center mb-4">
                <span className="material-symbols-outlined text-[20px]">fingerprint</span>
              </div>
              <h3 className="font-bold text-sm text-[#FFF8F0] mb-2">Cryptographic Evidence</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed">
                Direct queries to Stellar Horizon RPC, blockchain ledgers, and verified database replicas — not self-reported text.
              </p>
            </div>
          </div>

          <div className="p-6 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors">
            <div>
              <div className="w-10 h-10 rounded-xl bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center mb-4">
                <span className="material-symbols-outlined text-[20px]">rule</span>
              </div>
              <h3 className="font-bold text-sm text-[#FFF8F0] mb-2">Deterministic Rules</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed">
                Strict invariant engine where required conditions must pass 100% or the action is immediately failed.
              </p>
            </div>
          </div>

          <div className="p-6 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors">
            <div>
              <div className="w-10 h-10 rounded-xl bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center mb-4">
                <span className="material-symbols-outlined text-[20px]">published_with_changes</span>
              </div>
              <h3 className="font-bold text-sm text-[#FFF8F0] mb-2">Automated Remediation</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed">
                Structured, machine-actionable correction instructions dispatched back to the agent for recovery.
              </p>
            </div>
          </div>

          <div className="p-6 rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 flex flex-col justify-between hover:border-[#E08A3E]/40 transition-colors">
            <div>
              <div className="w-10 h-10 rounded-xl bg-[#21110B] border border-[#4A2B1D] text-[#E08A3E] flex items-center justify-center mb-4">
                <span className="material-symbols-outlined text-[20px]">lock</span>
              </div>
              <h3 className="font-bold text-sm text-[#FFF8F0] mb-2">Zero-Custody Architecture</h3>
              <p className="text-xs text-[#B9A99B] leading-relaxed">
                VeraOS never holds private keys, touches customer funds, or acts as custodian. Only cryptographic verdicts are emitted.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------- */}
      {/* 11. FAQ ACCORDION                                    */}
      {/* ---------------------------------------------------- */}
      <section id="faq" className="py-24 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto border-t border-[#4A2B1D]/40">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="text-xs font-bold uppercase tracking-widest text-[#E08A3E] mb-2">
            COMMON QUESTIONS
          </div>
          <h2 className="font-headline-lg text-3xl sm:text-5xl font-bold tracking-tight text-[#FFF8F0] mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-sm sm:text-base text-[#B9A99B] leading-relaxed">
            Everything you need to know about autonomous agent verification.
          </p>
        </div>

        <div className="space-y-4">
          {faqItems.map((item, idx) => {
            const isOpen = openFaq === idx;
            return (
              <div
                key={item.q}
                className="rounded-2xl bg-[#160C08] border border-[#4A2B1D]/80 overflow-hidden transition-colors"
              >
                <button
                  type="button"
                  onClick={() => setOpenFaq(isOpen ? null : idx)}
                  className="w-full px-6 py-5 flex items-center justify-between text-left text-sm sm:text-base font-semibold text-[#FFF8F0] hover:text-[#E08A3E] transition-colors"
                >
                  <span>{item.q}</span>
                  <span className={'material-symbols-outlined text-[20px] transition-transform duration-200 ' + (isOpen ? 'rotate-180 text-[#E08A3E]' : 'text-[#B9A99B]')}>
                    expand_more
                  </span>
                </button>
                {isOpen && (
                  <div className="px-6 pb-5 text-xs sm:text-sm text-[#B9A99B] leading-relaxed border-t border-white/5 pt-3">
                    {item.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* ---------------------------------------------------- */}
      {/* 12. FINAL CTA CARD CONTAINER                         */}
      {/* ---------------------------------------------------- */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto">
        <div className="rounded-3xl bg-gradient-to-b from-[#25130B] to-[#160C08] border border-[#E08A3E]/50 p-8 sm:p-14 text-center shadow-[0_20px_80px_rgba(201,106,43,0.25)] relative overflow-hidden">
          <div className="absolute -top-24 left-1/2 -translate-x-1/2 w-96 h-48 bg-[#E08A3E]/30 rounded-full blur-[90px] pointer-events-none" />

          <div className="relative z-10 max-w-2xl mx-auto">
            <div className="text-xs font-bold uppercase tracking-widest text-[#E08A3E] mb-3">
              START VERIFYING TODAY
            </div>
            <h2 className="font-headline-lg text-3xl sm:text-5xl font-bold tracking-tight text-[#FFF8F0] mb-4">
              Never pay for unverified work.
            </h2>
            <p className="text-sm sm:text-base text-[#B9A99B] leading-relaxed mb-8">
              Join autonomous agent developers and AI operators building zero-trust agent infrastructure on Stellar.
            </p>

            <div className="flex flex-wrap items-center justify-center gap-4">
              <Link
                to="/verify/new"
                className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl bg-[#C96A2B] hover:bg-[#E08A3E] text-white text-sm font-semibold transition-all shadow-[0_0_25px_rgba(201,106,43,0.5)] active:scale-[0.98]"
              >
                <span>Verify a task</span>
                <span className="material-symbols-outlined text-[16px]">arrow_forward</span>
              </Link>

              <a
                href={TELEGRAM_BOT_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl bg-[#1A0E08] hover:bg-[#2C1710] border border-[#4A2B1D] text-[#FFF8F0] text-sm font-medium transition-colors"
              >
                <svg className="w-4 h-4 fill-[#E08A3E]" viewBox="0 0 24 24">
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4.64 6.8c-.15 1.58-.8 5.42-1.13 7.19-.14.75-.42 1-.68 1.03-.58.05-1.02-.38-1.58-.75-.88-.58-1.38-.94-2.23-1.5-.99-.65-.35-1.01.22-1.59.15-.15 2.71-2.48 2.76-2.69a.2.2 0 00-.05-.18c-.06-.05-.14-.03-.21-.02-.09.02-1.49.95-4.22 2.79-.4.27-.76.41-1.08.4-.36-.01-1.04-.2-1.55-.37-.63-.2-1.12-.31-1.08-.66.02-.18.27-.36.74-.55 2.92-1.27 4.86-2.11 5.83-2.51 2.78-1.16 3.35-1.36 3.73-1.36.08 0 .27.02.39.12.1.08.13.19.14.27-.01.06.01.24 0 .38z" />
                </svg>
                <span>Open Telegram</span>
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------- */}
      {/* 13. FOOTER                                           */}
      {/* ---------------------------------------------------- */}
      <footer className="py-14 px-4 sm:px-6 lg:px-8 border-t border-[#4A2B1D]/50 bg-[#120906]">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-start justify-between gap-10">
          <div className="flex flex-col gap-3 max-w-sm">
            <Link to="/" className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-[#2C1710] to-[#1C0E09] border border-[#E08A3E]/40 flex items-center justify-center">
                <svg className="w-3.5 h-3.5 text-[#E08A3E]" fill="none" stroke="currentColor" strokeWidth="2.2" viewBox="0 0 24 24">
                  <polygon fill="#E08A3E" fillOpacity="0.2" points="12 2 21 7.5 21 16.5 12 22 3 16.5 3 7.5 12 2" />
                  <polyline points="12 2 12 12 21 7.5" />
                </svg>
              </div>
              <span className="font-bold text-sm tracking-tight text-[#FFF8F0]">
                Vera<span className="text-[#E08A3E]">OS</span>
              </span>
            </Link>
            <p className="text-xs text-[#B9A99B] leading-relaxed">
              Autonomous AI Agent Verification Infrastructure on the Stellar network. Zero-trust execution, deterministic receipts, and automated remediation.
            </p>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 gap-8 text-xs">
            <div>
              <div className="font-bold text-[#FFF8F0] uppercase tracking-wider mb-3">Product</div>
              <ul className="space-y-2 text-[#B9A99B]">
                <li><a href="#problem" className="hover:text-white transition-colors">Visibility Gap</a></li>
                <li><a href="#how-it-works" className="hover:text-white transition-colors">How it works</a></li>
                <li><a href="#interactive-verify" className="hover:text-white transition-colors">Interactive Demo</a></li>
                <li><Link to="/dashboard" className="hover:text-white transition-colors">Dashboard</Link></li>
              </ul>
            </div>

            <div>
              <div className="font-bold text-[#FFF8F0] uppercase tracking-wider mb-3">Resources</div>
              <ul className="space-y-2 text-[#B9A99B]">
                <li><Link to="/docs" className="hover:text-white transition-colors">Documentation</Link></li>
                <li><a href={GITHUB_REPO_URL} target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors">GitHub Repository</a></li>
                <li><a href="https://soroban-testnet.stellar.org" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors">Stellar RPC</a></li>
                <li><a href="https://horizon-testnet.stellar.org" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors">Stellar Horizon</a></li>
              </ul>
            </div>

            <div>
              <div className="font-bold text-[#FFF8F0] uppercase tracking-wider mb-3">Connect</div>
              <ul className="space-y-2 text-[#B9A99B]">
                <li><a href={TELEGRAM_BOT_URL} target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors">Telegram Bot (@Vera_Of_bot)</a></li>
                <li><Link to="/agents" className="hover:text-white transition-colors">Agent Registry</Link></li>
                <li><Link to="/agents/connect" className="hover:text-white transition-colors">Connect Agent</Link></li>
              </ul>
            </div>
          </div>
        </div>

        <div className="max-w-6xl mx-auto pt-8 mt-8 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-[#B9A99B]">
          <span>© 2026 VeraOS. Open-source verification infrastructure built on Stellar.</span>
          <div className="flex items-center gap-4">
            <span className="flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
              <span>Stellar Testnet Live</span>
            </span>
          </div>
        </div>
      </footer>
    </div>
  );
};
export default LandingPage;
